### ISSUE TITLE
Draft: V2

### ISSUE THREAD

**Issue by notrab** [notrab/shopkit#39]
Shopkit 2 will contain various "kits" that you can use. If you wish to embed Moltins customer auth functionality, you can import `CustomerKit` from `@moltin/shopkit`.

Shopkit Providers:

* CartKit
* CheckoutKit
* OrderKit
* CustomerKit

A typical header for a store built on Shopkit would use React Hooks to get the following info about the session:

```js
import React, { useContext } from 'react'

import { Cartkit, Customerkit } from '@moltin/shopkit'

export default function Header({ siteTitle }) {
  const { count, isEmpty } = useContext(Cartkit)
  const { loggedIn, user } = useContext(Customerkit)

  return (
    // ...
  )
}
```

**Comment by kvnwolf** [comment]
What about moving current connectors to hooks?

i.e

`useProduct()`, `useCart()`?
